<?php

/**
 * Player Name Transformations
 *
 * Maps original NBA player names to humorous parody alternatives.
 * Format: 'Original Name' => ['first_name' => 'New First', 'last_name' => 'New Last']
 *
 * Transformation patterns used:
 * - Phonetic swaps: Stephen → Steffen
 * - Letter additions: LeBron → LeBroom
 * - Letter removals: Anthony → Antony
 * - Similar names: Kevin → Kelvin
 * - Spelling tweaks: Jayson → Jason
 */

return [
    // A
    'A.J. Johnson' => ['first_name' => 'A.K.', 'last_name' => 'Johnston'],
    'A.J. Lawson' => ['first_name' => 'A.K.', 'last_name' => 'Lawsen'],
    'AJ Green' => ['first_name' => 'AK', 'last_name' => 'Greene'],
    'Aaron Gordon' => ['first_name' => 'Aron', 'last_name' => 'Gordan'],
    'Aaron Holiday' => ['first_name' => 'Aron', 'last_name' => 'Holliday'],
    'Aaron Nesmith' => ['first_name' => 'Aron', 'last_name' => 'Neesmith'],
    'Aaron Wiggins' => ['first_name' => 'Aron', 'last_name' => 'Wiggens'],
    'Ace Bailey' => ['first_name' => 'Aice', 'last_name' => 'Bayley'],
    'Adem Bona' => ['first_name' => 'Adam', 'last_name' => 'Bonna'],
    'Adou Thiero' => ['first_name' => 'Adoo', 'last_name' => 'Thierro'],
    'Ajay Mitchell' => ['first_name' => 'AJ', 'last_name' => 'Mitchel'],
    'Al Horford' => ['first_name' => 'Alf', 'last_name' => 'Horferd'],
    'Alex Antetokounmpo' => ['first_name' => 'Alek', 'last_name' => 'Antetokounpo'],
    'Alex Caruso' => ['first_name' => 'Alek', 'last_name' => 'Caroso'],
    'Alex Toohey' => ['first_name' => 'Alek', 'last_name' => 'Toohy'],
    'Alexandre Sarr' => ['first_name' => 'Alexandro', 'last_name' => 'Sar'],
    'Alijah Martin' => ['first_name' => 'Elijah', 'last_name' => 'Marten'],
    'Alperen Sengun' => ['first_name' => 'Alperin', 'last_name' => 'Sengoon'],
    'Amari Williams' => ['first_name' => 'Omari', 'last_name' => 'Willems'],
    'Amen Thompson' => ['first_name' => 'Amon', 'last_name' => 'Thomson'],
    'Amir Coffey' => ['first_name' => 'Ameer', 'last_name' => 'Coffee'],
    'Andre Drummond' => ['first_name' => 'Andray', 'last_name' => 'Drumond'],
    'Andre Jackson Jr.' => ['first_name' => 'Andray', 'last_name' => 'Jackson'],
    'Andrew Nembhard' => ['first_name' => 'Andru', 'last_name' => 'Nemhard'],
    'Andrew Wiggins' => ['first_name' => 'Andru', 'last_name' => 'Wiggens'],
    'Anfernee Simons' => ['first_name' => 'Anfernee', 'last_name' => 'Simmons'],
    'Anthony Black' => ['first_name' => 'Antony', 'last_name' => 'Blak'],
    'Anthony Davis' => ['first_name' => 'Antony', 'last_name' => 'Davies'],
    'Anthony Edwards' => ['first_name' => 'Antony', 'last_name' => 'Edwurds'],
    'Anthony Gill' => ['first_name' => 'Antony', 'last_name' => 'Gil'],
    'Antonio Reeves' => ['first_name' => 'Antonyo', 'last_name' => 'Reaves'],
    'Ariel Hukporti' => ['first_name' => 'Arial', 'last_name' => 'Hukporte'],
    'Asa Newell' => ['first_name' => 'Azza', 'last_name' => 'Newel'],
    'Ausar Thompson' => ['first_name' => 'Osar', 'last_name' => 'Thomson'],
    'Austin Reaves' => ['first_name' => 'Austen', 'last_name' => 'Reeves'],
    'Ayo Dosunmu' => ['first_name' => 'Aio', 'last_name' => 'Dosunmoo'],

    // B
    'Bam Adebayo' => ['first_name' => 'Bamm', 'last_name' => 'Adabayo'],
    'Baylor Scheierman' => ['first_name' => 'Baler', 'last_name' => 'Sheierman'],
    'Ben Saraf' => ['first_name' => 'Benn', 'last_name' => 'Seraph'],
    'Ben Sheppard' => ['first_name' => 'Benn', 'last_name' => 'Shepherd'],
    'Bennedict Mathurin' => ['first_name' => 'Benedict', 'last_name' => 'Mathuren'],
    'Bilal Coulibaly' => ['first_name' => 'Billal', 'last_name' => 'Coulibally'],
    'Bismack Biyombo' => ['first_name' => 'Bismark', 'last_name' => 'Biyomba'],
    'Blake Wesley' => ['first_name' => 'Blaze', 'last_name' => 'Wesly'],
    'Bobby Portis' => ['first_name' => 'Bobbie', 'last_name' => 'Portus'],
    'Bobi Klintman' => ['first_name' => 'Bobby', 'last_name' => 'Klintmann'],
    'Bogdan Bogdanovic' => ['first_name' => 'Bogden', 'last_name' => 'Bogdanovitch'],
    'Bones Hyland' => ['first_name' => 'Bonez', 'last_name' => 'Highland'],
    'Bradley Beal' => ['first_name' => 'Bradly', 'last_name' => 'Beale'],
    'Branden Carlson' => ['first_name' => 'Brandon', 'last_name' => 'Karlson'],
    'Brandin Podziemski' => ['first_name' => 'Brandon', 'last_name' => 'Podziemsky'],
    'Brandon Clarke' => ['first_name' => 'Branden', 'last_name' => 'Clark'],
    'Brandon Ingram' => ['first_name' => 'Branden', 'last_name' => 'Ingraham'],
    'Brandon Miller' => ['first_name' => 'Branden', 'last_name' => 'Millar'],
    'Brandon Williams' => ['first_name' => 'Branden', 'last_name' => 'Willems'],
    'Brice Sensabaugh' => ['first_name' => 'Bryce', 'last_name' => 'Sensabah'],
    'Bronny James' => ['first_name' => 'Bronnie', 'last_name' => 'Jaymes'],
    'Brook Lopez' => ['first_name' => 'Brooke', 'last_name' => 'Lopaz'],
    'Brooks Barnhizer' => ['first_name' => 'Brookes', 'last_name' => 'Barnhiser'],
    'Bruce Brown' => ['first_name' => 'Bruse', 'last_name' => 'Browne'],
    'Bryce McGowens' => ['first_name' => 'Brice', 'last_name' => 'McGowan'],
    'Bub Carrington' => ['first_name' => 'Bubb', 'last_name' => 'Carringten'],
    'Buddy Hield' => ['first_name' => 'Buddie', 'last_name' => 'Heild'],

    // C
    'C.J. McCollum' => ['first_name' => 'C.K.', 'last_name' => 'McCollom'],
    'CJ Huntley' => ['first_name' => 'CK', 'last_name' => 'Huntly'],
    'Cade Cunningham' => ['first_name' => 'Kade', 'last_name' => 'Cuningham'],
    'Caleb Houstan' => ['first_name' => 'Kaleb', 'last_name' => 'Houston'],
    'Caleb Love' => ['first_name' => 'Kaleb', 'last_name' => 'Luv'],
    'Caleb Martin' => ['first_name' => 'Kaleb', 'last_name' => 'Marten'],
    'Cam Christie' => ['first_name' => 'Kam', 'last_name' => 'Christy'],
    'Cam Johnson' => ['first_name' => 'Kam', 'last_name' => 'Johnston'],
    'Cam Spencer' => ['first_name' => 'Kam', 'last_name' => 'Spenser'],
    'Cam Thomas' => ['first_name' => 'Kam', 'last_name' => 'Tomas'],
    'Cam Whitmore' => ['first_name' => 'Kam', 'last_name' => 'Whitmoor'],
    'Caris LeVert' => ['first_name' => 'Karis', 'last_name' => 'LaVert'],
    'Carter Bryant' => ['first_name' => 'Karter', 'last_name' => 'Bryent'],
    'Cason Wallace' => ['first_name' => 'Kasen', 'last_name' => 'Wallis'],
    'Cedric Coward' => ['first_name' => 'Cedrik', 'last_name' => 'Cowerd'],
    'Chaz Lanier' => ['first_name' => 'Chazz', 'last_name' => 'Laneer'],
    'Chet Holmgren' => ['first_name' => 'Chett', 'last_name' => 'Holmgrin'],
    'Chris Boucher' => ['first_name' => 'Kris', 'last_name' => 'Boosher'],
    'Chris Livingston' => ['first_name' => 'Kris', 'last_name' => 'Livingsten'],
    'Chris Manon' => ['first_name' => 'Kris', 'last_name' => 'Mannen'],
    'Chris Paul' => ['first_name' => 'Kris', 'last_name' => 'Pawl'],
    'Chris Youngblood' => ['first_name' => 'Kris', 'last_name' => 'Youngblud'],
    'Christian Braun' => ['first_name' => 'Kristian', 'last_name' => 'Brown'],
    'Christian Koloko' => ['first_name' => 'Kristian', 'last_name' => 'Koloko'],
    'Chucky Hepburn' => ['first_name' => 'Chuckie', 'last_name' => 'Hepbern'],
    'Clint Capela' => ['first_name' => 'Klint', 'last_name' => 'Capella'],
    'Coby White' => ['first_name' => 'Koby', 'last_name' => 'Wite'],
    'Cody Williams' => ['first_name' => 'Kodie', 'last_name' => 'Willems'],
    'Colby Jones' => ['first_name' => 'Kolby', 'last_name' => 'Joanes'],
    'Cole Anthony' => ['first_name' => 'Coal', 'last_name' => 'Antony'],
    'Colin Castleton' => ['first_name' => 'Collin', 'last_name' => 'Castleten'],
    'Collin Gillespie' => ['first_name' => 'Colin', 'last_name' => 'Gillespee'],
    'Collin Murray-Boyles' => ['first_name' => 'Colin', 'last_name' => 'Murray-Boils'],
    'Collin Sexton' => ['first_name' => 'Colin', 'last_name' => 'Sexten'],
    'Cooper Flagg' => ['first_name' => 'Kooper', 'last_name' => 'Flag'],
    'Corey Kispert' => ['first_name' => 'Cory', 'last_name' => 'Kispurt'],
    'Craig Porter Jr.' => ['first_name' => 'Creg', 'last_name' => 'Portar'],
    'Curtis Jones' => ['first_name' => 'Kurtis', 'last_name' => 'Joanes'],

    // D
    'D\'Angelo Russell' => ['first_name' => 'DeAngelo', 'last_name' => 'Russel'],
    'DaRon Holmes II' => ['first_name' => 'Darron', 'last_name' => 'Holms'],
    'Daeqwon Plowden' => ['first_name' => 'Daequan', 'last_name' => 'Plowdan'],
    'Dain Dainja' => ['first_name' => 'Dane', 'last_name' => 'Danja'],
    'Dalen Terry' => ['first_name' => 'Dalin', 'last_name' => 'Terri'],
    'Dalton Knecht' => ['first_name' => 'Dolton', 'last_name' => 'Necht'],
    'Damian Lillard' => ['first_name' => 'Damien', 'last_name' => 'Lilard'],
    'Daniel Gafford' => ['first_name' => 'Danial', 'last_name' => 'Gaford'],
    'Daniss Jenkins' => ['first_name' => 'Denis', 'last_name' => 'Jenkyns'],
    'Danny Wolf' => ['first_name' => 'Dany', 'last_name' => 'Wolfe'],
    'Dante Exum' => ['first_name' => 'Donte', 'last_name' => 'Exom'],
    'Dario Saric' => ['first_name' => 'Daryo', 'last_name' => 'Sarik'],
    'Darius Garland' => ['first_name' => 'Daryus', 'last_name' => 'Garlend'],
    'David Jones-Garcia' => ['first_name' => 'Davide', 'last_name' => 'Jones-Garcya'],
    'Davion Mitchell' => ['first_name' => 'Davyon', 'last_name' => 'Mitchel'],
    'Day\'Ron Sharpe' => ['first_name' => 'DayRon', 'last_name' => 'Sharp'],
    'De\'Aaron Fox' => ['first_name' => 'DeAron', 'last_name' => 'Foxx'],
    'De\'Andre Hunter' => ['first_name' => 'DeAndre', 'last_name' => 'Huntar'],
    'De\'Anthony Melton' => ['first_name' => 'DeAnthony', 'last_name' => 'Melten'],
    'DeMar DeRozan' => ['first_name' => 'DeMar', 'last_name' => 'DeRosen'],
    'Dean Wade' => ['first_name' => 'Deen', 'last_name' => 'Waid'],
    'Deandre Ayton' => ['first_name' => 'DeAndre', 'last_name' => 'Ayten'],
    'Dejounte Murray' => ['first_name' => 'DeJonte', 'last_name' => 'Murry'],
    'Deni Avdija' => ['first_name' => 'Denny', 'last_name' => 'Avdiya'],
    'Dennis Schroder' => ['first_name' => 'Denis', 'last_name' => 'Schroeder'],
    'Dereck Lively II' => ['first_name' => 'Derek', 'last_name' => 'Livelee'],
    'Derik Queen' => ['first_name' => 'Derek', 'last_name' => 'Qween'],
    'Derrick Jones Jr.' => ['first_name' => 'Derek', 'last_name' => 'Joanes'],
    'Derrick White' => ['first_name' => 'Derek', 'last_name' => 'Wite'],
    'Desmond Bane' => ['first_name' => 'Dezmond', 'last_name' => 'Bain'],
    'Devin Booker' => ['first_name' => 'Devon', 'last_name' => 'Bookar'],
    'Devin Carter' => ['first_name' => 'Devon', 'last_name' => 'Kartar'],
    'Devin Vassell' => ['first_name' => 'Devon', 'last_name' => 'Vassel'],
    'Dillon Brooks' => ['first_name' => 'Dylan', 'last_name' => 'Brookes'],
    'Domantas Sabonis' => ['first_name' => 'Domantos', 'last_name' => 'Sabonus'],
    'Dominick Barlow' => ['first_name' => 'Dominik', 'last_name' => 'Barlo'],
    'Donovan Clingan' => ['first_name' => 'Donavan', 'last_name' => 'Klangan'],
    'Donovan Mitchell' => ['first_name' => 'Donavan', 'last_name' => 'Mitchel'],
    'Donte DiVincenzo' => ['first_name' => 'Dante', 'last_name' => 'DeVincenzo'],
    'Dorian Finney-Smith' => ['first_name' => 'Dorean', 'last_name' => 'Finny-Smith'],
    'Doug McDermott' => ['first_name' => 'Dug', 'last_name' => 'McDermit'],
    'Drake Powell' => ['first_name' => 'Drayke', 'last_name' => 'Powel'],
    'Draymond Green' => ['first_name' => 'Dreymond', 'last_name' => 'Greene'],
    'Drew Eubanks' => ['first_name' => 'Dru', 'last_name' => 'Youbanks'],
    'Drew Peterson' => ['first_name' => 'Dru', 'last_name' => 'Petersen'],
    'Dru Smith' => ['first_name' => 'Drew', 'last_name' => 'Smithe'],
    'Duncan Robinson' => ['first_name' => 'Dunkan', 'last_name' => 'Robinsen'],
    'Duop Reath' => ['first_name' => 'Dwop', 'last_name' => 'Reeth'],
    'Dwight Powell' => ['first_name' => 'Dwaight', 'last_name' => 'Powel'],
    'Dylan Cardwell' => ['first_name' => 'Dillon', 'last_name' => 'Kardwell'],
    'Dylan Harper' => ['first_name' => 'Dillon', 'last_name' => 'Harpar'],
    'Dyson Daniels' => ['first_name' => 'Dison', 'last_name' => 'Danielz'],

    // E
    'E.J. Liddell' => ['first_name' => 'E.K.', 'last_name' => 'Lidell'],
    'EJ Harkless' => ['first_name' => 'EK', 'last_name' => 'Harklis'],
    'Egor Demin' => ['first_name' => 'Igor', 'last_name' => 'Demmin'],
    'Eli John Ndiaye' => ['first_name' => 'Ely', 'last_name' => 'Ndiay'],
    'Emanuel Miller' => ['first_name' => 'Emmanuel', 'last_name' => 'Millar'],
    'Emoni Bates' => ['first_name' => 'Imoni', 'last_name' => 'Baits'],
    'Enrique Freeman' => ['first_name' => 'Enriqe', 'last_name' => 'Freemen'],
    'Eric Gordon' => ['first_name' => 'Erik', 'last_name' => 'Gordan'],
    'Ethan Thompson' => ['first_name' => 'Ethen', 'last_name' => 'Thomson'],
    'Evan Mobley' => ['first_name' => 'Evin', 'last_name' => 'Moblee'],

    // F
    'Franz Wagner' => ['first_name' => 'Frans', 'last_name' => 'Wagnar'],
    'Fred VanVleet' => ['first_name' => 'Ferd', 'last_name' => 'VanFleet'],

    // G
    'G.G. Jackson' => ['first_name' => 'G.J.', 'last_name' => 'Jakson'],
    'Gabe Vincent' => ['first_name' => 'Gabe', 'last_name' => 'Vinsent'],
    'Garrett Temple' => ['first_name' => 'Garret', 'last_name' => 'Tempel'],
    'Gary Harris' => ['first_name' => 'Garry', 'last_name' => 'Haris'],
    'Gary Payton II' => ['first_name' => 'Garry', 'last_name' => 'Paton'],
    'Gary Trent' => ['first_name' => 'Garry', 'last_name' => 'Trant'],
    'Georges Niang' => ['first_name' => 'George', 'last_name' => 'Nyang'],
    'Giannis Antetokounmpo' => ['first_name' => 'Yannis', 'last_name' => 'Antetokounpo'],
    'Goga Bitadze' => ['first_name' => 'Gogo', 'last_name' => 'Bitadzi'],
    'Gradey Dick' => ['first_name' => 'Grady', 'last_name' => 'Dik'],
    'Grant Williams' => ['first_name' => 'Grent', 'last_name' => 'Willems'],
    'Grayson Allen' => ['first_name' => 'Greyson', 'last_name' => 'Allan'],
    'Guerschon Yabusele' => ['first_name' => 'Gershon', 'last_name' => 'Yabuselee'],
    'Gui Santos' => ['first_name' => 'Gee', 'last_name' => 'Santoz'],

    // H
    'Harrison Barnes' => ['first_name' => 'Harison', 'last_name' => 'Barns'],
    'Harrison Ingram' => ['first_name' => 'Harison', 'last_name' => 'Ingraham'],
    'Haywood Highsmith' => ['first_name' => 'Heywood', 'last_name' => 'Hysmith'],
    'Herb Jones' => ['first_name' => 'Herby', 'last_name' => 'Joanes'],
    'Hugo Gonzalez' => ['first_name' => 'Hughgo', 'last_name' => 'Gonzales'],
    'Hunter Dickinson' => ['first_name' => 'Huntar', 'last_name' => 'Dickinsen'],
    'Hunter Sallis' => ['first_name' => 'Huntar', 'last_name' => 'Saliss'],
    'Hunter Tyson' => ['first_name' => 'Huntar', 'last_name' => 'Tison'],

    // I
    'Immanuel Quickley' => ['first_name' => 'Emanuel', 'last_name' => 'Quikley'],
    'Isaac Jones' => ['first_name' => 'Issac', 'last_name' => 'Joanes'],
    'Isaac Okoro' => ['first_name' => 'Issac', 'last_name' => 'Okorro'],
    'Isaiah Collier' => ['first_name' => 'Isiah', 'last_name' => 'Colleer'],
    'Isaiah Crawford' => ['first_name' => 'Isiah', 'last_name' => 'Crawferd'],
    'Isaiah Hartenstein' => ['first_name' => 'Isiah', 'last_name' => 'Hartenstine'],
    'Isaiah Jackson' => ['first_name' => 'Isiah', 'last_name' => 'Jakson'],
    'Isaiah Joe' => ['first_name' => 'Isiah', 'last_name' => 'Jo'],
    'Isaiah Livers' => ['first_name' => 'Isiah', 'last_name' => 'Livars'],
    'Isaiah Stevens' => ['first_name' => 'Isiah', 'last_name' => 'Stevans'],
    'Isaiah Stewart' => ['first_name' => 'Isiah', 'last_name' => 'Stuart'],
    'Ivica Zubac' => ['first_name' => 'Ivika', 'last_name' => 'Zoobac'],

    // J
    'J.D. Davison' => ['first_name' => 'J.T.', 'last_name' => 'Davisen'],
    'Ja Morant' => ['first_name' => 'Jay', 'last_name' => 'Morent'],
    'Ja\'Kobe Walter' => ['first_name' => 'JaKobe', 'last_name' => 'Waltar'],
    'Jabari Smith Jr.' => ['first_name' => 'Jabarie', 'last_name' => 'Smithe'],
    'Jabari Walker' => ['first_name' => 'Jabarie', 'last_name' => 'Walkar'],
    'Jackson Rowe' => ['first_name' => 'Jakson', 'last_name' => 'Row'],
    'Jacob Toppin' => ['first_name' => 'Jakob', 'last_name' => 'Topin'],
    'Jaden Hardy' => ['first_name' => 'Jayden', 'last_name' => 'Hardie'],
    'Jaden Ivey' => ['first_name' => 'Jayden', 'last_name' => 'Ivee'],
    'Jaden McDaniels' => ['first_name' => 'Jayden', 'last_name' => 'McDanials'],
    'Jaden Springer' => ['first_name' => 'Jayden', 'last_name' => 'Springar'],
    'Jae\'Sean Tate' => ['first_name' => 'JaySean', 'last_name' => 'Tait'],
    'Jahmir Young' => ['first_name' => 'Jamir', 'last_name' => 'Yung'],
    'Jahmyl Telfort' => ['first_name' => 'Jamil', 'last_name' => 'Telfert'],
    'Jaime Jaquez Jr.' => ['first_name' => 'Jamie', 'last_name' => 'Jakez'],
    'Jake LaRavia' => ['first_name' => 'Jaik', 'last_name' => 'LaRavya'],
    'Jakob Poeltl' => ['first_name' => 'Jacob', 'last_name' => 'Poeltal'],
    'Jalen Brunson' => ['first_name' => 'Jaylen', 'last_name' => 'Brunsen'],
    'Jalen Duren' => ['first_name' => 'Jaylen', 'last_name' => 'Duran'],
    'Jalen Green' => ['first_name' => 'Jaylen', 'last_name' => 'Greene'],
    'Jalen Johnson' => ['first_name' => 'Jaylen', 'last_name' => 'Johnston'],
    'Jalen Pickett' => ['first_name' => 'Jaylen', 'last_name' => 'Piket'],
    'Jalen Smith' => ['first_name' => 'Jaylen', 'last_name' => 'Smithe'],
    'Jalen Suggs' => ['first_name' => 'Jaylen', 'last_name' => 'Sugs'],
    'Jalen Williams' => ['first_name' => 'Jaylen', 'last_name' => 'Willems'],
    'Jalen Wilson' => ['first_name' => 'Jaylen', 'last_name' => 'Wilsen'],
    'Jamal Cain' => ['first_name' => 'Jamall', 'last_name' => 'Kane'],
    'Jamal Murray' => ['first_name' => 'Jamall', 'last_name' => 'Murry'],
    'Jamal Shead' => ['first_name' => 'Jamall', 'last_name' => 'Shed'],
    'James Harden' => ['first_name' => 'Jaymes', 'last_name' => 'Harding'],
    'James Wiseman' => ['first_name' => 'Jaymes', 'last_name' => 'Wissman'],
    'Jamir Watkins' => ['first_name' => 'Jahmir', 'last_name' => 'Watkyns'],
    'Jamison Battle' => ['first_name' => 'Jameson', 'last_name' => 'Battel'],
    'Jarace Walker' => ['first_name' => 'Jarase', 'last_name' => 'Walkar'],
    'Jared McCain' => ['first_name' => 'Jarred', 'last_name' => 'McKain'],
    'Jaren Jackson Jr.' => ['first_name' => 'Jarren', 'last_name' => 'Jakson'],
    'Jarkel Joiner' => ['first_name' => 'Jarkal', 'last_name' => 'Joyner'],
    'Jarred Vanderbilt' => ['first_name' => 'Jared', 'last_name' => 'Vanderbillt'],
    'Jarrett Allen' => ['first_name' => 'Jaret', 'last_name' => 'Allan'],
    'Jase Richardson' => ['first_name' => 'Jayce', 'last_name' => 'Richardsen'],
    'Jason Preston' => ['first_name' => 'Jayson', 'last_name' => 'Presten'],
    'Javon Small' => ['first_name' => 'Javone', 'last_name' => 'Smal'],
    'Javonte Cooke' => ['first_name' => 'Javonte', 'last_name' => 'Cook'],
    'Javonte Green' => ['first_name' => 'Javonte', 'last_name' => 'Greene'],
    'Jaxson Hayes' => ['first_name' => 'Jakson', 'last_name' => 'Hays'],
    'Jay Huff' => ['first_name' => 'Jai', 'last_name' => 'Huf'],
    'Jaylen Brown' => ['first_name' => 'Jalen', 'last_name' => 'Browne'],
    'Jaylen Clark' => ['first_name' => 'Jalen', 'last_name' => 'Clarke'],
    'Jaylen Wells' => ['first_name' => 'Jalen', 'last_name' => 'Welles'],
    'Jaylin Williams' => ['first_name' => 'Jaelin', 'last_name' => 'Willems'],
    'Jaylon Tyson' => ['first_name' => 'Jailan', 'last_name' => 'Tison'],
    'Jayson Tatum' => ['first_name' => 'Jason', 'last_name' => 'Taytum'],
    'Jeff Green' => ['first_name' => 'Jef', 'last_name' => 'Greene'],
    'Jerami Grant' => ['first_name' => 'Jeramie', 'last_name' => 'Grent'],
    'Jeremiah Fears' => ['first_name' => 'Jerimiah', 'last_name' => 'Feers'],
    'Jeremy Sochan' => ['first_name' => 'Jeremie', 'last_name' => 'Sochin'],
    'Jericho Sims' => ['first_name' => 'Jeriko', 'last_name' => 'Simms'],
    'Jett Howard' => ['first_name' => 'Jet', 'last_name' => 'Howerd'],
    'Jevon Carter' => ['first_name' => 'Javon', 'last_name' => 'Kartar'],
    'Jimmy Butler' => ['first_name' => 'Jimmi', 'last_name' => 'Butlar'],
    'Joan Beringer' => ['first_name' => 'John', 'last_name' => 'Beringur'],
    'Jock Landale' => ['first_name' => 'Jok', 'last_name' => 'Landayl'],
    'Joe Ingles' => ['first_name' => 'Jo', 'last_name' => 'Ingels'],
    'Joel Embiid' => ['first_name' => 'Joel', 'last_name' => 'Embeed'],
    'John Collins' => ['first_name' => 'Jon', 'last_name' => 'Colins'],
    'John Konchar' => ['first_name' => 'Jon', 'last_name' => 'Konchar'],
    'John Tonje' => ['first_name' => 'Jon', 'last_name' => 'Tonjay'],
    'Johni Broome' => ['first_name' => 'Johnie', 'last_name' => 'Broom'],
    'Johnny Furphy' => ['first_name' => 'Jonny', 'last_name' => 'Furphee'],
    'Johnny Juzang' => ['first_name' => 'Jonny', 'last_name' => 'Juzeng'],
    'Jonas Valanciunas' => ['first_name' => 'Jonnas', 'last_name' => 'Valanciunis'],
    'Jonathan Isaac' => ['first_name' => 'Johnathan', 'last_name' => 'Issac'],
    'Jonathan Kuminga' => ['first_name' => 'Johnathan', 'last_name' => 'Kumingo'],
    'Jonathan Mogbo' => ['first_name' => 'Johnathan', 'last_name' => 'Mogba'],
    'Jordan Clarkson' => ['first_name' => 'Jordon', 'last_name' => 'Klarkson'],
    'Jordan Goodwin' => ['first_name' => 'Jordon', 'last_name' => 'Gudwin'],
    'Jordan Hawkins' => ['first_name' => 'Jordon', 'last_name' => 'Hawkyns'],
    'Jordan McLaughlin' => ['first_name' => 'Jordon', 'last_name' => 'McLauchlin'],
    'Jordan Miller' => ['first_name' => 'Jordon', 'last_name' => 'Millar'],
    'Jordan Poole' => ['first_name' => 'Jordon', 'last_name' => 'Pool'],
    'Jordan Walsh' => ['first_name' => 'Jordon', 'last_name' => 'Wolsh'],
    'Jose Alvarado' => ['first_name' => 'Hose', 'last_name' => 'Alvarada'],
    'Josh Giddey' => ['first_name' => 'Jash', 'last_name' => 'Giddy'],
    'Josh Green' => ['first_name' => 'Jash', 'last_name' => 'Greene'],
    'Josh Hart' => ['first_name' => 'Jash', 'last_name' => 'Harte'],
    'Josh Minott' => ['first_name' => 'Jash', 'last_name' => 'Minot'],
    'Josh Okogie' => ['first_name' => 'Jash', 'last_name' => 'Okogee'],
    'Jrue Holiday' => ['first_name' => 'Drew', 'last_name' => 'Holliday'],
    'Julian Champagnie' => ['first_name' => 'Julien', 'last_name' => 'Champagne'],
    'Julian Phillips' => ['first_name' => 'Julien', 'last_name' => 'Philips'],
    'Julian Strawther' => ['first_name' => 'Julien', 'last_name' => 'Strauther'],
    'Julius Randle' => ['first_name' => 'Julias', 'last_name' => 'Randal'],
    'Justin Champagnie' => ['first_name' => 'Justen', 'last_name' => 'Champagne'],
    'Justin Edwards' => ['first_name' => 'Justen', 'last_name' => 'Edwurds'],
    'Jusuf Nurkic' => ['first_name' => 'Josef', 'last_name' => 'Nurkitch'],

    // K
    'KJ Simpson' => ['first_name' => 'KG', 'last_name' => 'Simpsen'],
    'Kam Jones' => ['first_name' => 'Cam', 'last_name' => 'Joanes'],
    'Karl-Anthony Towns' => ['first_name' => 'Carl-Anthony', 'last_name' => 'Townes'],
    'Karlo Matkovic' => ['first_name' => 'Carlo', 'last_name' => 'Matkovitch'],
    'Kasparas Jakucionis' => ['first_name' => 'Kasper', 'last_name' => 'Jakucyonis'],
    'Kawhi Leonard' => ['first_name' => 'Kawi', 'last_name' => 'Lennard'],
    'Keaton Wallace' => ['first_name' => 'Keeton', 'last_name' => 'Wallis'],
    'Keegan Murray' => ['first_name' => 'Kegan', 'last_name' => 'Murry'],
    'Kel\'el Ware' => ['first_name' => 'Kelel', 'last_name' => 'Wear'],
    'Keldon Johnson' => ['first_name' => 'Keldan', 'last_name' => 'Johnston'],
    'Kelly Olynyk' => ['first_name' => 'Kellie', 'last_name' => 'Olynik'],
    'Kelly Oubre' => ['first_name' => 'Kellie', 'last_name' => 'Oobray'],
    'Kenrich Williams' => ['first_name' => 'Kenrick', 'last_name' => 'Willems'],
    'Kentavious Caldwell-Pope' => ['first_name' => 'Kentavius', 'last_name' => 'Caldwell-Pape'],
    'Keon Ellis' => ['first_name' => 'Keyon', 'last_name' => 'Elis'],
    'Keon Johnson' => ['first_name' => 'Keyon', 'last_name' => 'Johnston'],
    'Keshad Johnson' => ['first_name' => 'Keshod', 'last_name' => 'Johnston'],
    'Kevin Durant' => ['first_name' => 'Kelvin', 'last_name' => 'Durrant'],
    'Kevin Huerter' => ['first_name' => 'Kelvin', 'last_name' => 'Huertar'],
    'Kevin Love' => ['first_name' => 'Kelvin', 'last_name' => 'Luv'],
    'Kevin McCullar Jr' => ['first_name' => 'Kelvin', 'last_name' => 'McCullar'],
    'Kevin Porter Jr.' => ['first_name' => 'Kelvin', 'last_name' => 'Portar'],
    'Kevon Harris' => ['first_name' => 'Kevin', 'last_name' => 'Haris'],
    'Kevon Looney' => ['first_name' => 'Kevin', 'last_name' => 'Loonie'],
    'Keyonte George' => ['first_name' => 'Keyonte', 'last_name' => 'Jorge'],
    'Khaman Maluach' => ['first_name' => 'Kaman', 'last_name' => 'Maluch'],
    'Khris Middleton' => ['first_name' => 'Chris', 'last_name' => 'Middelton'],
    'Klay Thompson' => ['first_name' => 'Clay', 'last_name' => 'Thomson'],
    'Kobe Brown' => ['first_name' => 'Koby', 'last_name' => 'Browne'],
    'Kobe Sanders' => ['first_name' => 'Koby', 'last_name' => 'Sandars'],
    'Koby Brea' => ['first_name' => 'Kobe', 'last_name' => 'Breya'],
    'Kon Knueppel' => ['first_name' => 'Conn', 'last_name' => 'Knuepel'],
    'Kris Dunn' => ['first_name' => 'Chris', 'last_name' => 'Dun'],
    'Kris Murray' => ['first_name' => 'Chris', 'last_name' => 'Murry'],
    'Kristaps Porzingis' => ['first_name' => 'Kristops', 'last_name' => 'Porzingus'],
    'Kyle Anderson' => ['first_name' => 'Kile', 'last_name' => 'Andersen'],
    'Kyle Filipowski' => ['first_name' => 'Kile', 'last_name' => 'Filipowsky'],
    'Kyle Kuzma' => ['first_name' => 'Kile', 'last_name' => 'Koozma'],
    'Kyle Lowry' => ['first_name' => 'Kile', 'last_name' => 'Lowrie'],
    'Kyrie Irving' => ['first_name' => 'Kyree', 'last_name' => 'Irvin'],
    'Kyshawn George' => ['first_name' => 'Kishawn', 'last_name' => 'Jorge'],

    // L
    'LaMelo Ball' => ['first_name' => 'LaMello', 'last_name' => 'Bal'],
    'Lachlan Olbrich' => ['first_name' => 'Lachlen', 'last_name' => 'Olbrik'],
    'Landry Shamet' => ['first_name' => 'Landrie', 'last_name' => 'Shamett'],
    'Larry Nance Jr.' => ['first_name' => 'Lary', 'last_name' => 'Nanse'],
    'Lauri Markkanen' => ['first_name' => 'Laurie', 'last_name' => 'Markanen'],
    'LeBron James' => ['first_name' => 'LeBroom', 'last_name' => 'Jaymes'],
    'Leonard Miller' => ['first_name' => 'Lenard', 'last_name' => 'Millar'],
    'Liam McNeeley' => ['first_name' => 'Lyam', 'last_name' => 'McNeely'],
    'Lindy Waters III' => ['first_name' => 'Lindie', 'last_name' => 'Watars'],
    'Lonzo Ball' => ['first_name' => 'Lonza', 'last_name' => 'Bal'],
    'Luguentz Dort' => ['first_name' => 'Lugenz', 'last_name' => 'Durt'],
    'Luka Doncic' => ['first_name' => 'Luca', 'last_name' => 'Donchich'],
    'Luka Garza' => ['first_name' => 'Luca', 'last_name' => 'Garzza'],
    'Luke Kennard' => ['first_name' => 'Luc', 'last_name' => 'Kennerd'],
    'Luke Kornet' => ['first_name' => 'Luc', 'last_name' => 'Kornett'],
    'Luke Travers' => ['first_name' => 'Luc', 'last_name' => 'Travars'],

    // M
    'Malaki Branham' => ['first_name' => 'Malakie', 'last_name' => 'Branhem'],
    'Malik Monk' => ['first_name' => 'Malek', 'last_name' => 'Munk'],
    'Marcus Sasser' => ['first_name' => 'Markus', 'last_name' => 'Sassar'],
    'Marcus Smart' => ['first_name' => 'Markus', 'last_name' => 'Smarte'],
    'Mark Sears' => ['first_name' => 'Marc', 'last_name' => 'Seers'],
    'Mark Williams' => ['first_name' => 'Marc', 'last_name' => 'Willems'],
    'Marvin Bagley III' => ['first_name' => 'Marven', 'last_name' => 'Baglee'],
    'Mason Plumlee' => ['first_name' => 'Masen', 'last_name' => 'Plumley'],
    'Matas Buzelis' => ['first_name' => 'Mattas', 'last_name' => 'Buzelius'],
    'Matisse Thybulle' => ['first_name' => 'Matise', 'last_name' => 'Thybul'],
    'Max Christie' => ['first_name' => 'Maks', 'last_name' => 'Christy'],
    'Max Shulga' => ['first_name' => 'Maks', 'last_name' => 'Shoolga'],
    'Max Strus' => ['first_name' => 'Maks', 'last_name' => 'Struss'],
    'Maxi Kleber' => ['first_name' => 'Maxy', 'last_name' => 'Klebar'],
    'Maxime Raynaud' => ['first_name' => 'Maximum', 'last_name' => 'Rayno'],
    'Micah Peavy' => ['first_name' => 'Mika', 'last_name' => 'Peavie'],
    'Michael Porter Jr.' => ['first_name' => 'Mikael', 'last_name' => 'Portar'],
    'Mikal Bridges' => ['first_name' => 'Mikael', 'last_name' => 'Bridgez'],
    'Mike Conley' => ['first_name' => 'Mick', 'last_name' => 'Conlee'],
    'Miles Bridges' => ['first_name' => 'Myles', 'last_name' => 'Bridgez'],
    'Miles Kelly' => ['first_name' => 'Myles', 'last_name' => 'Kellie'],
    'Miles McBride' => ['first_name' => 'Myles', 'last_name' => 'McBryde'],
    'Mitchell Robinson' => ['first_name' => 'Mitchel', 'last_name' => 'Robinsen'],
    'Mohamed Diawara' => ['first_name' => 'Mohammed', 'last_name' => 'Diawarra'],
    'Moritz Wagner' => ['first_name' => 'Moriz', 'last_name' => 'Wagnar'],
    'Moses Moody' => ['first_name' => 'Mose', 'last_name' => 'Moodie'],
    'Mouhamed Gueye' => ['first_name' => 'Mohamed', 'last_name' => 'Guey'],
    'Moussa Cisse' => ['first_name' => 'Mousa', 'last_name' => 'Cissy'],
    'Moussa Diabate' => ['first_name' => 'Mousa', 'last_name' => 'Diabatte'],
    'Myles Turner' => ['first_name' => 'Miles', 'last_name' => 'Turnar'],
    'Myron Gardner' => ['first_name' => 'Miron', 'last_name' => 'Gardnar'],

    // N
    'N\'Faly Dante' => ['first_name' => 'NFaly', 'last_name' => 'Donte'],
    'Nae\'Qwan Tomlin' => ['first_name' => 'NaeQwan', 'last_name' => 'Tomlyn'],
    'Naji Marshall' => ['first_name' => 'Najee', 'last_name' => 'Marshal'],
    'Naz Reid' => ['first_name' => 'Nazz', 'last_name' => 'Reed'],
    'Neemias Queta' => ['first_name' => 'Nemias', 'last_name' => 'Keta'],
    'Nick Richards' => ['first_name' => 'Nik', 'last_name' => 'Richurds'],
    'Nick Smith Jr.' => ['first_name' => 'Nik', 'last_name' => 'Smithe'],
    'Nickeil Alexander-Walker' => ['first_name' => 'Nikel', 'last_name' => 'Alexander-Walkar'],
    'Nicolas Batum' => ['first_name' => 'Nikolas', 'last_name' => 'Battum'],
    'Nicolas Claxton' => ['first_name' => 'Nikolas', 'last_name' => 'Clakston'],
    'Nigel Hayes-Davis' => ['first_name' => 'Nygel', 'last_name' => 'Hays-Davis'],
    'Nikola Djurisic' => ['first_name' => 'Nikola', 'last_name' => 'Djurisich'],
    'Nikola Jokic' => ['first_name' => 'Nikola', 'last_name' => 'Jokitch'],
    'Nikola Jovic' => ['first_name' => 'Nikola', 'last_name' => 'Jovitch'],
    'Nikola Topic' => ['first_name' => 'Nikola', 'last_name' => 'Topik'],
    'Nikola Vucevic' => ['first_name' => 'Nikola', 'last_name' => 'Vucevitch'],
    'Nique Clifford' => ['first_name' => 'Nick', 'last_name' => 'Clifferd'],
    'Noa Essengue' => ['first_name' => 'Noah', 'last_name' => 'Essengoo'],
    'Noah Clowney' => ['first_name' => 'Noa', 'last_name' => 'Clowny'],
    'Noah Penda' => ['first_name' => 'Noa', 'last_name' => 'Pendah'],
    'Nolan Traore' => ['first_name' => 'Nolen', 'last_name' => 'Traoray'],
    'Norman Powell' => ['first_name' => 'Normen', 'last_name' => 'Powel'],

    // O
    'O.G. Anunoby' => ['first_name' => 'O.J.', 'last_name' => 'Anunobe'],
    'Obi Toppin' => ['first_name' => 'Obie', 'last_name' => 'Topin'],
    'Ochai Agbaji' => ['first_name' => 'Ochie', 'last_name' => 'Agbajee'],
    'Olivier-Maxence Prosper' => ['first_name' => 'Oliver', 'last_name' => 'Prosperr'],
    'Onyeka Okongwu' => ['first_name' => 'Onyeka', 'last_name' => 'Okongoo'],
    'Orlando Robinson' => ['first_name' => 'Orlendo', 'last_name' => 'Robinsen'],
    'Oscar Tshiebwe' => ['first_name' => 'Oskar', 'last_name' => 'Sheebway'],
    'Oso Ighodaro' => ['first_name' => 'Osso', 'last_name' => 'Ighodarro'],
    'Ousmane Dieng' => ['first_name' => 'Ousmaine', 'last_name' => 'Diang'],

    // P
    'PJ Hall' => ['first_name' => 'PK', 'last_name' => 'Hal'],
    'PJ Washington' => ['first_name' => 'PK', 'last_name' => 'Washingten'],
    'Pacome Dadiet' => ['first_name' => 'Pakom', 'last_name' => 'Dadyet'],
    'Paolo Banchero' => ['first_name' => 'Paulo', 'last_name' => 'Bancharo'],
    'Pascal Siakam' => ['first_name' => 'Paskal', 'last_name' => 'Siakum'],
    'Pat Connaughton' => ['first_name' => 'Patt', 'last_name' => 'Conaughton'],
    'Pat Spencer' => ['first_name' => 'Patt', 'last_name' => 'Spenser'],
    'Patrick Williams' => ['first_name' => 'Patrik', 'last_name' => 'Willems'],
    'Paul George' => ['first_name' => 'Paulo', 'last_name' => 'Jorge'],
    'Paul Reed' => ['first_name' => 'Paulo', 'last_name' => 'Reid'],
    'Payton Pritchard' => ['first_name' => 'Peyton', 'last_name' => 'Prichard'],
    'Pelle Larsson' => ['first_name' => 'Pel', 'last_name' => 'Larsen'],
    'Pete Nance' => ['first_name' => 'Peet', 'last_name' => 'Nanse'],
    'Peyton Watson' => ['first_name' => 'Payton', 'last_name' => 'Watsen'],

    // Q
    'Quentin Grimes' => ['first_name' => 'Quintin', 'last_name' => 'Grimez'],
    'Quenton Jackson' => ['first_name' => 'Quinton', 'last_name' => 'Jakson'],
    'Quinten Post' => ['first_name' => 'Quentin', 'last_name' => 'Poste'],

    // R
    'R.J. Barrett' => ['first_name' => 'R.K.', 'last_name' => 'Barret'],
    'Rasheer Fleming' => ['first_name' => 'Rashir', 'last_name' => 'Flemming'],
    'RayJ Dennis' => ['first_name' => 'RayK', 'last_name' => 'Denis'],
    'Rayan Rupert' => ['first_name' => 'Ryan', 'last_name' => 'Rupart'],
    'Reed Sheppard' => ['first_name' => 'Reid', 'last_name' => 'Shepherd'],
    'Riley Minix' => ['first_name' => 'Rylee', 'last_name' => 'Miniks'],
    'Rob Dillingham' => ['first_name' => 'Robb', 'last_name' => 'Dilingham'],
    'Robert Williams' => ['first_name' => 'Roburt', 'last_name' => 'Willems'],
    'Rocco Zikarsky' => ['first_name' => 'Rocko', 'last_name' => 'Zikarskie'],
    'Ron Harper Jr.' => ['first_name' => 'Ronn', 'last_name' => 'Harpar'],
    'Ron Holland' => ['first_name' => 'Ronn', 'last_name' => 'Hollend'],
    'Royce O\'Neale' => ['first_name' => 'Roice', 'last_name' => 'ONeal'],
    'Rudy Gobert' => ['first_name' => 'Ruddy', 'last_name' => 'Gobare'],
    'Rui Hachimura' => ['first_name' => 'Ruee', 'last_name' => 'Hachimurra'],
    'Russell Westbrook' => ['first_name' => 'Russel', 'last_name' => 'Westbrooke'],
    'Ryan Dunn' => ['first_name' => 'Rayan', 'last_name' => 'Dun'],
    'Ryan Kalkbrenner' => ['first_name' => 'Rayan', 'last_name' => 'Kalkbrener'],
    'Ryan Nembhard' => ['first_name' => 'Rayan', 'last_name' => 'Nemhard'],
    'Ryan Rollins' => ['first_name' => 'Rayan', 'last_name' => 'Rolins'],

    // S
    'Saddiq Bey' => ['first_name' => 'Sadiq', 'last_name' => 'Bay'],
    'Sam Hauser' => ['first_name' => 'Samm', 'last_name' => 'Howser'],
    'Sam Merrill' => ['first_name' => 'Samm', 'last_name' => 'Merill'],
    'Sandro Mamukelashvili' => ['first_name' => 'Sondro', 'last_name' => 'Mamukelashvilly'],
    'Santi Aldama' => ['first_name' => 'Santee', 'last_name' => 'Aldamma'],
    'Scoot Henderson' => ['first_name' => 'Skoot', 'last_name' => 'Hendersen'],
    'Scottie Barnes' => ['first_name' => 'Scotty', 'last_name' => 'Barns'],
    'Scotty Pippen Jr.' => ['first_name' => 'Scottie', 'last_name' => 'Pippin'],
    'Shaedon Sharpe' => ['first_name' => 'Shaydon', 'last_name' => 'Sharp'],
    'Shai Gilgeous-Alexander' => ['first_name' => 'Shy', 'last_name' => 'Gilgeous-Alexender'],
    'Sharife Cooper' => ['first_name' => 'Shareef', 'last_name' => 'Coopar'],
    'Sidy Cissoko' => ['first_name' => 'Siddy', 'last_name' => 'Sissoko'],
    'Simone Fontecchio' => ['first_name' => 'Simon', 'last_name' => 'Fonteckio'],
    'Sion James' => ['first_name' => 'Zion', 'last_name' => 'Jaymes'],
    'Spencer Dinwiddie' => ['first_name' => 'Spenser', 'last_name' => 'Dinwiddy'],
    'Spencer Jones' => ['first_name' => 'Spenser', 'last_name' => 'Joanes'],
    'Stephen Curry' => ['first_name' => 'Steffen', 'last_name' => 'Currie'],
    'Stephon Castle' => ['first_name' => 'Stefan', 'last_name' => 'Kastle'],
    'Steven Adams' => ['first_name' => 'Stephen', 'last_name' => 'Addams'],
    'Svi Mykhailiuk' => ['first_name' => 'Svee', 'last_name' => 'Mykhailiook'],

    // T
    'T.J. McConnell' => ['first_name' => 'T.K.', 'last_name' => 'McConnel'],
    'Taelon Peter' => ['first_name' => 'Taylon', 'last_name' => 'Petar'],
    'Tamar Bates' => ['first_name' => 'Tamir', 'last_name' => 'Baits'],
    'Tari Eason' => ['first_name' => 'Tarri', 'last_name' => 'Easen'],
    'Taurean Prince' => ['first_name' => 'Torean', 'last_name' => 'Prinse'],
    'Taylor Hendricks' => ['first_name' => 'Tayler', 'last_name' => 'Hendriks'],
    'Terance Mann' => ['first_name' => 'Terrance', 'last_name' => 'Man'],
    'Terrence Shannon Jr.' => ['first_name' => 'Terence', 'last_name' => 'Shanon'],
    'Terry Rozier' => ['first_name' => 'Terri', 'last_name' => 'Rozeer'],
    'Thanasis Antetokounmpo' => ['first_name' => 'Thanassis', 'last_name' => 'Antetokounpo'],
    'Thomas Bryant' => ['first_name' => 'Tomas', 'last_name' => 'Bryent'],
    'Thomas Sorber' => ['first_name' => 'Tomas', 'last_name' => 'Sorbar'],
    'Tidjane Salaun' => ['first_name' => 'Tidjani', 'last_name' => 'Salaoon'],
    'Tim Hardaway Jr.' => ['first_name' => 'Timm', 'last_name' => 'Hardway'],
    'Tobias Harris' => ['first_name' => 'Tobyas', 'last_name' => 'Haris'],
    'Tolu Smith' => ['first_name' => 'Talu', 'last_name' => 'Smithe'],
    'Tony Bradley' => ['first_name' => 'Toni', 'last_name' => 'Bradlee'],
    'Tosan Evbuomwan' => ['first_name' => 'Tosin', 'last_name' => 'Evbuomwon'],
    'Toumani Camara' => ['first_name' => 'Tumani', 'last_name' => 'Kamara'],
    'Trae Young' => ['first_name' => 'Trey', 'last_name' => 'Yung'],
    'Trayce Jackson-Davis' => ['first_name' => 'Trace', 'last_name' => 'Jakson-Davis'],
    'Tre Johnson' => ['first_name' => 'Trey', 'last_name' => 'Johnston'],
    'Tre Jones' => ['first_name' => 'Trey', 'last_name' => 'Joanes'],
    'Tre Mann' => ['first_name' => 'Trey', 'last_name' => 'Man'],
    'Trendon Watford' => ['first_name' => 'Trenden', 'last_name' => 'Watferd'],
    'Trentyn Flowers' => ['first_name' => 'Trentin', 'last_name' => 'Flowars'],
    'Trey Alexander' => ['first_name' => 'Tre', 'last_name' => 'Alexender'],
    'Trey Jemison' => ['first_name' => 'Tre', 'last_name' => 'Jemisen'],
    'Trey Murphy' => ['first_name' => 'Tre', 'last_name' => 'Murphee'],
    'Tristan Vukcevic' => ['first_name' => 'Tristen', 'last_name' => 'Vukcevich'],
    'Tristan da Silva' => ['first_name' => 'Tristen', 'last_name' => 'Da Silva'],
    'Ty Jerome' => ['first_name' => 'Tie', 'last_name' => 'Jeroma'],
    'Tyler Herro' => ['first_name' => 'Tylar', 'last_name' => 'Hero'],
    'Tyler Kolek' => ['first_name' => 'Tylar', 'last_name' => 'Kolik'],
    'Tyrese Haliburton' => ['first_name' => 'Tyreese', 'last_name' => 'Haliburten'],
    'Tyrese Martin' => ['first_name' => 'Tyreese', 'last_name' => 'Marten'],
    'Tyrese Maxey' => ['first_name' => 'Tyreese', 'last_name' => 'Maxy'],
    'Tyrese Proctor' => ['first_name' => 'Tyreese', 'last_name' => 'Proktor'],
    'Tyson Etienne' => ['first_name' => 'Tison', 'last_name' => 'Etienn'],
    'Tyus Jones' => ['first_name' => 'Tius', 'last_name' => 'Joanes'],

    // V
    'VJ Edgecombe' => ['first_name' => 'VK', 'last_name' => 'Edgecomb'],
    'Victor Wembanyama' => ['first_name' => 'Viktor', 'last_name' => 'Wembanyamma'],
    'Vince Williams Jr.' => ['first_name' => 'Vinse', 'last_name' => 'Willems'],
    'Vit Krejci' => ['first_name' => 'Vitt', 'last_name' => 'Krejtsi'],
    'Vladislav Goldin' => ['first_name' => 'Vladislev', 'last_name' => 'Goldyn'],

    // W
    'Walker Kessler' => ['first_name' => 'Walkar', 'last_name' => 'Kesslar'],
    'Walter Clayton' => ['first_name' => 'Waltar', 'last_name' => 'Claiton'],
    'Wendell Carter Jr.' => ['first_name' => 'Wendel', 'last_name' => 'Kartar'],
    'Will Richard' => ['first_name' => 'Wil', 'last_name' => 'Richerd'],
    'Will Riley' => ['first_name' => 'Wil', 'last_name' => 'Rylee'],

    // X
    'Xavier Tillman' => ['first_name' => 'Zavier', 'last_name' => 'Tilman'],

    // Y
    'Yang Hansen' => ['first_name' => 'Yong', 'last_name' => 'Hanson'],
    'Yanic Konan Niederhauser' => ['first_name' => 'Yanik', 'last_name' => 'Niederhausar'],
    'Yves Missi' => ['first_name' => 'Eves', 'last_name' => 'Missy'],

    // Z
    'Zaccharie Risacher' => ['first_name' => 'Zacharie', 'last_name' => 'Risachar'],
    'Zach Collins' => ['first_name' => 'Zak', 'last_name' => 'Colins'],
    'Zach Edey' => ['first_name' => 'Zak', 'last_name' => 'Edee'],
    'Zach LaVine' => ['first_name' => 'Zak', 'last_name' => 'LaVeen'],
    'Zeke Nnaji' => ['first_name' => 'Zeek', 'last_name' => 'Najee'],
    'Ziaire Williams' => ['first_name' => 'Zaire', 'last_name' => 'Willems'],
    'Zion Williamson' => ['first_name' => 'Sion', 'last_name' => 'Willamson'],
];
